spring.application.name=Restaurant_Backend


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=postgres
spring.datasource.password=Anil$1234

# JPA (Hibernate) Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
